services:
  # --- MINIO (DATA LAKE) ---
  minio:
    image: minio/minio
    container_name: minio-datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      TZ: "America/Sao_Paulo" 
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # --- POSTGRES (METADADOS DO AIRFLOW) ---
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- AIRFLOW (ORQUESTRADOR) ---
  airflow-webserver:
    build: .
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      # Configuração para conectar no MinIO como se fosse S3 AWS
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_DEFAULT_REGION=us-east-1
      - TZ=America/Sao_Paulo
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_DEFAULT_REGION=us-east-1
      - TZ=America/Sao_Paulo
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - airflow-init
    restart: always

  # Serviço auxiliar para inicializar o banco de dados na primeira vez
  airflow-init:
    build: .
    container_name: airflow_init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres
    command: version
    # Script para criar o usuário admin automaticamente
    entrypoint: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Matheus --lastname TCC --role Admin --email admin@example.com --password admin || true"
      
  # --- DASHBOARD (STREAMLIT) ---
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: dashboard-app
    ports:
      - "8501:8501"
    environment:
      - MINIO_ENDPOINT=http://minio-datalake:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - TZ=America/Sao_Paulo
    depends_on:
      - minio
    volumes:
      - ./dashboard.py:/app/dashboard.py

    restart: always
volumes:
  minio_data:
  postgres_data: